build:
	./mk_q3keys.py > q3keys.py

test:
	@echo 'Testing with python 2'
	python2 ./q3colors.py
	python2 ./q3config.py
	python2 ./q3keys.py
	python2 ./q3maps.py
	python2 ./q3path.py
	python2 ./q3stat.py
	python2 ./q3specialchars.py
	@echo 'Testing with python 3'
	python3 ./q3colors.py
	python3 ./q3config.py
	python3 ./q3keys.py
	python3 ./q3maps.py
	python3 ./q3path.py
	python3 ./q3stat.py
	python3 ./q3specialchars.py
