#!/usr/bin/python
# -*- coding: utf-8 -*-

LABEL = 'Openarena Configurator'
COMMANDS = {}

def C(name, description=None, usage=None, alias=None):
    if name in COMMANDS:
        raise Exception("Duplicate: %s" % name)

    COMMANDS[name] = {
        'name':         name,
        'description':  description,
        'usage':        usage,
        'alias':        alias
    }

C('cmdlist',        'List all available commands')
C('cinematic')
C('rehashbans')
C('net_restart',    'Restart network dependent stuff')
C('which',          'Locate the path of a file', '<FILE>')
C('s_info')
C('s_stop')
C('s_list')
C('stopmusic',      'Stop playing music')
C('music')
C('play')
C('gfxinfo')
C('screenshotJPEG', 'Save screenshot as <FILE>.jpg', '<FILE>')
C('screenshot',     'Save screenshot as <FILE>.tga', '<FILE>')
C('modelist',       'List all available screen resolutions')
C('modellist')
C('skinlist')
C('shaderlist')
C('imagelist')
C('minimize')
C('stopvideo')
C('video')
C('model')
C('fs_referencedList')
C('fs_openedList')
C('showip',         'Show IP address')
C('serverstatus')
C('ping')
C('rcon')
C('globalservers')
C('localservers')
C('reconnect')
C('connect')
C('stoprecord')
C('demo')
C('record')
C('disconnect')
C('vid_restart',    'Restart graphics related stuff', alias='restart_video')
C('snd_restart',    'Restart sound related stuff',    alias='restart_sound')
C('clientinfo')
C('configstrings')
C('cmd')
C('-voiprecord')
C('+voiprecord')
C('-mlook')
C('+mlook')
C('-button14')
C('+button14')
C('-button13')
C('+button13')
C('-button12')
C('+button12')
C('-button11')
C('+button11')
C('-button10')
C('+button10')
C('-button9')
C('+button9')
C('-button8')
C('+button8')
C('-button7')
C('+button7')
C('-button6')
C('+button6')
C('-button5')
C('+button5')
C('-button4')
C('+button4')
C('-button3')
C('+button3')
C('-button2')
C('+button2')
C('-button1')
C('+button1')
C('-button0')
C('+button0')
C('-attack')
C('+attack')
C('-speed',         alias='-run')
C('+speed',         alias='+run')
C('-moveright')
C('+moveright')
C('-moveleft')
C('+moveleft')
C('-strafe')
C('+strafe')
C('-lookdown')
C('+lookdown')
C('-lookup')
C('+lookup')
C('-back')
C('+back')
C('-forward')
C('+forward')
C('-right')
C('+right')
C('-left')
C('+left')
C('-movedown',      alias='-crouch')
C('+movedown',      alias='+crouch')
C('-moveup',        alias='-jump')
C('+moveup',        alias='+jump')
C('centerview')
C('condump',        'Dump console contents to <FILE>', '<FILE>')
C('clear',          'Clear console')
C('messagemode4',   'Enter attacker chat mode', alias='messagemode_attacker')
C('messagemode3',   'Enter target chat mode',   alias='messagemode_target')
C('messagemode2',   'Enter team chat mode',     alias='messagemode_team')
C('messagemode',    'Enter global chat mode',   alias='messagemode_say')
C('toggleconsole',  'Show/Hide the Console')
C('flushbans')
C('exceptdel')
C('bandel')
C('exceptaddr')
C('banaddr')
C('listbans')
C('killserver')
C('spdevmap')
C('spmap')
C('devmap')
C('map')
C('sectorlist')
C('map_restart')
C('dumpuser')
C('systeminfo')
C('serverinfo')
C('status')
C('clientkick')
C('kick')
C('heartbeat')
C('vminfo')
C('vmprofile')
C('in_restart',     'Restart input related stuff',  alias='restart_input')
C('meminfo')
C('exec',           'Execute <FILE[.cfg]> inside config directory', '<FILE[.cfg]>')
C('set')
C('seta',           'Set variable <VAR> to <VALUE> and archive it', '<VAR> <VALUE>')
C('setu')
C('sets')
C('bind',           'Bind <KEY> to <COMMAND>',                      '<KEY> <COMMAND>')
C('unbindall',      'Reset all keybindings')
C('game_restart')
C('writeconfig',    'Save the current configuration to disk')
C('changeVectors')
C('quit',           'Quit the game')
C('setenv')
C('touchFile')
C('fdir')
C('dir')
C('path')
C('bindlist')
C('unbind')
C('wait')
C('echo',           'Write <string> to console', '<string>')
C('cvar_restart')
C('cvarlist')
C('unset')
C('reset')
C('toggle',         'Toggle the value of <VAR>', '<VAR> <value1>, [<value2>, <valueN>...]')
C('print',          'Print value of <VAR> to console', '<VAR>')
C('vstr',           'Execute contents of <VAR> as a config script', '<VAR>')
del C
